### ISSUE TITLE
Import button is gray

### ISSUE THREAD

**Issue by ghost** [nathanwoulfe/tabulate#16]
In the backoffice in the setting the "Import" button is grayed out - is there some config issue on our end that is causing this? Thank you! 
![Screenshot 2021-06-15 090012](https://user-images.githubusercontent.com/6393405/122090555-b9390680-cdbc-11eb-99bd-bf10ab9c6389.png)

**Comment by nathanwoulfe** [comment]
Hey @rbproworks which version is this? I have a beta that's been pending release for ages, keep forgetting to push it - if you're not on that version, would you mind trying it?

Pretty sure it's cosmetic fixes only, so wouldn't be surprised if this was still an issue...

**Comment by ghost** [comment]
Hi Nathan - it's Tabulate 3.0.4 (and we're running Umbraco 8.12.2). Trying out the beta might be an option but it probably won't be my call since it's production code, but I can possibly try it locally to see if it makes a difference. Do you happen to know what logic or conditions would be the reason for the Import button being disabled? Thanks for your quick reply!

**Comment by nathanwoulfe** [comment]
Most likely cause is my dodgy code 🙄

I'll have a look and get back to you. Will wrap up the beta as a proper release too.

**Comment by ghost** [comment]
Ah no problem! Hey your code is great... it's complex stuff...no complaints from me!

**Comment by nathanwoulfe** [comment]
@rbproworks pretty sure I've found the (definitely dodgy) cause - the check for `newVal.length` should be `> 0`, not `=== 0`.

If you feel like patching that in the compile javascript, it should resolve the problem. It's not a perfect fix, but will allow importing to work correctly

https://github.com/nathanwoulfe/tabulate/blob/8bac1861ea3718f0f321d8719601c5b17e99faf8/Tabulate/App_Plugins/Tabulate/Backoffice/controllers/tabulate.settings.controller.js#L155

**Comment by ghost** [comment]
That's terrific Nathan - we'll give that a try!

**Comment by nathanwoulfe** [comment]
Hey @rbproworks, this took a bit longer than I'd hoped, but RC is building now, will be on NuGet soon. 

RC is the dual-targeted framework/netcore release, so any other feedback would be great too
