### ISSUE TITLE
"Admin Only" and "Wide" settings always true

### ISSUE THREAD

**Issue by bowserm** [nathanwoulfe/tabulate#19]
We found that no matter how we toggle the `adminOnly` and `wide` prevalue settings on our Umbraco 8 site with Tabulate 3.0.4, the values were always considered `true`. When we looked into the code, we found that the values were coming back as `"1"` and `"0"`. `"0"` is a truthy value.

**Comment by bowserm** [comment]
I have submitted a PR for this. I have adjusted both of the boolean prevalues, `adminOnly` and `wide` so that we compare them to `true` like `$scope.model.config.adminOnly == true` which is working better.

PR: https://github.com/nathanwoulfe/tabulate/pull/18/files

**Comment by nathanwoulfe** [comment]
Hi @bowserm, I missed this when it was raised, sorry. I've merged these changes into the v4 RC, which will be on NuGet shortly.

The RC is the dual-targeted Umbraco 8/9 release, so interested in any other feedback too.
