### ISSUE TITLE
RTE not translating Umbraco links

### ISSUE THREAD

**Issue by waycooljen** [nathanwoulfe/tabulate#2]
When using an RTE for a data column, when you create a link that points to a local page within Umbraco, instead of displaying the actual url - it uses something like this; /{localLink:umb://document/1f513cb55b604f56aea02be427dafd50} - so when you click on the link you get an error.

**Comment by nathanwoulfe** [comment]
Using the property converter to render the content? I might have forgotten to convert the links in the converter...

**Comment by nathanwoulfe** [comment]
Have added v2.2.3 - the property converter now parses internal links in RTE fields. Will still need to render using @Html.Raw(cell) to ensure encoding, but the link will now be correct. Nuget will be updated shortly.
