### ISSUE TITLE
URL type shows up as a String type in the cells model

### ISSUE THREAD

**Issue by protherj** [nathanwoulfe/tabulate#21]
I have a url in one of the columns and I'd like to be able to render it as a link.  However, when I select the "URL" type in the column it comes through as a String in the razor.  Should it be a URI?  Or is there a way to check the type of the cell that is being renderd?

Thanks,
Jason

**Comment by nathanwoulfe** [comment]
Hey Jason, I'd say that's because there's no value conversion in the PVC for URL-type fields. I'm planning on a netcore migration in the next couple of weeks (should be pretty minor since there's very little C# to deal with), I can address this as part of those changes.

**Comment by nathanwoulfe** [comment]
Hi @protherj I've added changes in the v4 RC, to return the URL field type as a URI (provided the string value can parse). If it can't be parsed and is therefore not a valid URL, converter returns null.

The RC is the dual-targeted Umbraco 8/9 release, so interested in any other feedback too. Release will be on NuGet shortly.

**Comment by protherj** [comment]
Thanks, I'm just getting back to seeing this.  I'll take a look and see if this works for us, thanks!

**Comment by protherj** [comment]
Nathan,

When I updated Nuget to the 4.0 RC the back-office editor displayed only the JSON information

![image](https://user-images.githubusercontent.com/167112/134562000-c451a87e-9379-4f16-b419-c352b1abb31b.png)

Is there a migration that should be running or something I need to do?  I did bump the clientDependency.config.


I'm also getting an error on the front-end about there being no Headers object.  Did the API change at all?  

Last question: I'm concerned about using an RC in a project that may be deployed in a month or so.  What is the timeline for release?


Thanks,
Jason

**Comment by nathanwoulfe** [comment]
Hi @protherj not sure why that would be. Any errors logged in the console?

I'll have a look when I have a few minutes, it won't be anything major - I'm guessing something related to the change to multi-target.

**Comment by nathanwoulfe** [comment]
Hey @protherj I've had another look, can't see any issues when running from source. I've bumped to rc-004, once that's built I'll try installing clean and see what happens.

There's very little functional change for v4 outside of supporting Umbraco 9, so not sure what's happening in your environment...

**Comment by protherj** [comment]
Could it be an issue with the Nuget package?

**Comment by nathanwoulfe** [comment]
I've just tried the following:
- clean umbraco 8 install
- install tabulate 3.2.0
- configure, add content
- update to rc-004
- works as expected

Have you checked that the app_plugins files exist? Screenshot looks very much like the editor isn't loading. Also worth checking the data type is still referencing the correct editor

**Comment by protherj** [comment]
There is something in the App_Plugins, but I suspect its the older version perhaps?

Here's the package.manifest detail:

```
{   
    //you can define multiple editors   
    propertyEditors: [      
        {
            alias: "Tabulate.Umbraco",
            name: "Tabulate",
            editor: {
                view: "~/App_Plugins/Tabulate/Backoffice/views/tabulate.html",
				valueType: 'JSON'
            },
			prevalues: {
				fields: [
					{
						label: "Wide",
						key: "wide",
						view: "boolean"
					},
					{
						label: "Can access settings",
						key: "canAccessSettings",
						description: "Comma-separated list of group aliases to have access to Tabulate settings",
						view: 'textstring'
					},
					{
						label: "Custom view",
						key: "customView",
						description: "Path to a custom view for rendering add/edit dialogs",
						view: 'textstring'
					},
					{
						label: "Overlay size",
						key: "customViewSize",
						description: "Overlay size for edit and custom views ('small', 'medium', 'large')",
						view: 'textstring'
					},
					{
						label: "Google Maps API key",
						key: "mapsApiKey",
						description: "API key for Google Maps in address dialogs",
						view: 'textstring'
					},					
					{
						label: "Rich text editor",
						key: "rte",
						description: "Rich text editor configuration",
						view: 'views/propertyeditors/rte/rte.prevalues.html'
					}
				]
			}			
        }
    ],
    //array of files we want to inject into the application on app_start
    javascript: [
		'~/App_Plugins/Tabulate/Backoffice/tabulate.js'
	],
	css: [
		'~/App_Plugins/Tabulate/Backoffice/styles.css'
    ]
}
```

**Comment by nathanwoulfe** [comment]
Hey @protherj that definitely doesn't look right - the editor alias should be nw.tabulate not umbraco.tabulate. 

That said, I just now published v4.0.0, recommend grabbing that one.

**Comment by protherj** [comment]
Sounds good, I'll try that

**Comment by protherj** [comment]
Yep, updating to 4.0.0 got my back-office working 👍 

And this enabled me to detect the URL and display it properly in the View!  Thanks!
