### ISSUE TITLE
Sorting Rows

### ISSUE THREAD

**Issue by waycooljen** [nathanwoulfe/tabulate#3]
In the backend of Umbraco 7.10.1, I have a table already created.  If I move my cursor over a row it looks like I should be able to change the row order, but it doesn't do anything.  

Manually sorting would be a great feature because users make mistakes in data entry or they want to go back to the table and add new data, but have it appear in a specific row.

**Comment by nathanwoulfe** [comment]
That's broken - absolutely should allow sorting by dragging the rows. Will fix it.

**Comment by nathanwoulfe** [comment]
And should be fixed now - sorting needs to be enabled in the settings overlay (currentcolumns tab, there's a dropdown with ascending, descending and manual). If that is set to manual, the sort option appears in each table row and serves as the sort handle.

Idea here is that the order can be enforced (asc, desc based on the label text) or left manual for the editors to determine.
