### ISSUE TITLE
Import CSV/JSON feature is hidden

### ISSUE THREAD

**Issue by btcjt** [nathanwoulfe/tabulate#4]
I was unable to find an easy way to import a CSV. I ended up seeing "style: display: hidden" on an import button and removed this style, in which I was able to import a CSV no problem. Is there a reason why this feature is hidden?

**Comment by nathanwoulfe** [comment]
Hi @yoshinstine, I'll need to double check, but from memory, the steps to upload are to paste the new data into the field, which should display the upload buttons (either JSON or CSV). If that's what you did, and it wasn't working, I'm guessing there's a watch on the textarea that isn't firing. Will look into it.

**Comment by nathanwoulfe** [comment]
Hyi @yoshinstine, I've just released v2.3.1 which improves the UI for importing data. The import option will be disabled until the textarea containing the data is modified - this is to prevent reimporting the existing dataset, which is pointless but will chew up geolocation calls.

So the flow is - 
 - remove existing data from textarea
 - paste in new data
 - import button is enabled
 - select type (json/csv) from the import dropdown
 - submit

Release will be on nuget shortly, will also up on Our.Umbraco.
